# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
- package-ecosystem: "npm"
  directory: "/"
  commit-message:
    prefix: "npm"
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
  groups:
    npm-prod-dependencies:
      applies-to: version-updates
      dependency-type: "production"
    npm-dev-dependencies:
      dependency-type: "development"
      applies-to: version-updates
- package-ecosystem: "pip"
  directory: "/"
  commit-message:
    prefix: "pip"
    prefix-development: "pip-dev"
  labels: [ 'chore ' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    pip-dev-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
      dependency-type: development
    pip-prod-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
      dependency-type: production
  allow:
  - dependency-type: all
