version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "actions"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        applies-to: version-updates
        patterns:
        - "*"

  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "npm"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
    schedule:
      interval: "weekly"
    groups:
      pip-dev-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      pip-prod-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "patch"
    allow:
      - dependency-type: all
      
