name: Deploy to server

on:
  workflow_dispatch:
    inputs:
      update_server:
        description: "Update the server before deployment"
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id && chmod 600 ~/.ssh/id
          echo "${{ vars.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          echo "Host remote
            User root
            Hostname www.openstreetmap.ng
            IdentityFile ~/.ssh/id
          " > ~/.ssh/config

      - name: Deploy
        run: |
          ssh remote <<\EOF
            set -euxo pipefail

            : Fetch changes
            cd /data/osm-ng
            git fetch origin "${{ github.sha }}"

            : Setup build environment
            WORKTREE_DIR=$(mktemp -d osm-ng-build.XXXXXXXXXX)
            cleanup() {
              if [ -d "$WORKTREE_DIR" ]; then
                cd /data/osm-ng
                git worktree remove --force "$WORKTREE_DIR"
              fi
            }
            trap cleanup EXIT ERR
            git worktree add --detach "$WORKTREE_DIR" "${{ github.sha }}"

            : Build the new system configuration
            cd "$WORKTREE_DIR"
            cp config/services-test.nix /etc/nixos/services.nix
            if [ "${{ inputs.update_server }}" = "true" ]; then
              RESULT_PATH=$(nixos-rebuild build --no-out-link --upgrade)
            else
              RESULT_PATH=$(nixos-rebuild build --no-out-link)
            fi

            : Stop services
            systemctl stop osm-ng-dev

            : Reset to the specified commit
            cd /data/osm-ng
            git reset --hard "${{ github.sha }}"

            : Activate the new configuration
            "$RESULT_PATH/bin/switch-to-configuration" switch
          EOF
