name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29

      - name: Generate cache key
        run: |
          nixpkgs_hash=$(grep -Eo 'archive/[0-9a-f]{40}\.tar\.gz' shell.nix | cut -d'/' -f2 | cut -d'.' -f1)
          echo "CACHE_KEY=${{ runner.os }}-$nixpkgs_hash" >> $GITHUB_ENV

      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ env.CACHE_KEY }}

      - name: Cache files and packages
        uses: actions/cache@v4
        with:
          key: pkg-${{ env.CACHE_KEY }}-${{ hashFiles('uv.lock', 'bun.lock') }}
          path: |
            ~/.cache/uv
            ~/.bun/install/cache
            .venv
            node_modules
            app/static/img/element/_generated
            config/locale/gnu
            config/locale/i18next
            config/locale/postprocess

      - name: Start services
        run: |
          nix-shell --pure --run "dev-start"

      - name: Run tests
        env:
          POSTGRES_LOG: 1
        run: |
          nix-shell --pure --run "run-tests --extended --term"
